spring:
  application:
    name: tech-equipment-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
  profiles:
    active: ${PROFILE:dev}
  mvc:
    problemdetails:
      enabled: true
server:
  servlet:
    context-path: /api
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expires-in-minutes: ${JWT_ACCESS_EXPIRES_IN_MINUTES:10}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expires-in-days: ${JWT_REFRESH_EXPIRES_IN_DAYS:7}

