management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSURE:"*"}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}
  metrics:
    enable:
      all: true
    tags:
      application: tech-equipment-manager
logging:
  level:
    org.springframework.security: DEBUG